package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.sincon.sanita.services.model.CategoriaStruttura;
import it.sincon.sanita.services.service.CategoriaStrutturaLocalServiceUtil;

/**
 * The extended model base implementation for the CategoriaStruttura service. Represents a row in the &quot;SANITAREST_CategoriaStruttura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CategoriaStrutturaImpl}.
 * </p>
 *
 * @author Sincon
 * @see CategoriaStrutturaImpl
 * @see it.sincon.sanita.services.model.CategoriaStruttura
 * @generated
 */
public abstract class CategoriaStrutturaBaseImpl
    extends CategoriaStrutturaModelImpl implements CategoriaStruttura {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a categoria struttura model instance should use the {@link CategoriaStruttura} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CategoriaStrutturaLocalServiceUtil.addCategoriaStruttura(this);
        } else {
            CategoriaStrutturaLocalServiceUtil.updateCategoriaStruttura(this);
        }
    }
}
