package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.sincon.sanita.services.model.CFG_CategorieAbilitate;
import it.sincon.sanita.services.service.CFG_CategorieAbilitateLocalServiceUtil;

/**
 * The extended model base implementation for the CFG_CategorieAbilitate service. Represents a row in the &quot;SANITAREST_CFG_CategorieAbilitate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CFG_CategorieAbilitateImpl}.
 * </p>
 *
 * @author Sincon
 * @see CFG_CategorieAbilitateImpl
 * @see it.sincon.sanita.services.model.CFG_CategorieAbilitate
 * @generated
 */
public abstract class CFG_CategorieAbilitateBaseImpl
    extends CFG_CategorieAbilitateModelImpl implements CFG_CategorieAbilitate {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a c f g_ categorie abilitate model instance should use the {@link CFG_CategorieAbilitate} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CFG_CategorieAbilitateLocalServiceUtil.addCFG_CategorieAbilitate(this);
        } else {
            CFG_CategorieAbilitateLocalServiceUtil.updateCFG_CategorieAbilitate(this);
        }
    }
}
