package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.sincon.sanita.services.model.News;
import it.sincon.sanita.services.service.NewsLocalServiceUtil;

/**
 * The extended model base implementation for the News service. Represents a row in the &quot;SANITAREST_News&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsImpl}.
 * </p>
 *
 * @author Sincon
 * @see NewsImpl
 * @see it.sincon.sanita.services.model.News
 * @generated
 */
public abstract class NewsBaseImpl extends NewsModelImpl implements News {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a news model instance should use the {@link News} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            NewsLocalServiceUtil.addNews(this);
        } else {
            NewsLocalServiceUtil.updateNews(this);
        }
    }
}
