package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import it.sincon.sanita.services.model.RispostaPaginata;
import it.sincon.sanita.services.model.RispostaPaginataModel;
import it.sincon.sanita.services.model.StrutturaSanitaria;
import it.sincon.sanita.services.model.StrutturaSanitariaModel;
import it.sincon.sanita.services.model.StrutturaSanitariaSoap;

import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * The base model implementation for the StrutturaSanitaria service. Represents a row in the &quot;SANITAREST_StrutturaSanitaria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link it.sincon.sanita.services.model.StrutturaSanitariaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StrutturaSanitariaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitariaImpl
 * @see it.sincon.sanita.services.model.StrutturaSanitaria
 * @see it.sincon.sanita.services.model.StrutturaSanitariaModel
 * @generated
 */
@JSON(strict = true)
public class RispostaPaginataModelImpl<T> extends BaseModelImpl<RispostaPaginata<T>>
    implements RispostaPaginataModel<T> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a struttura sanitaria model instance should use the {@link it.sincon.sanita.services.model.StrutturaSanitaria} interface instead.
     */
    public static final String TABLE_NAME = "SANITAREST_StrutturaSanitaria";
    public static final Object[][] TABLE_COLUMNS = {
    		{ "primaryKey", Types.BIGINT },
    		{ "numFound", Types.INTEGER },
            { "start", Types.INTEGER },
            { "data", Types.ARRAY }
        };
    public static final String TABLE_SQL_CREATE = "";
    public static final String TABLE_SQL_DROP = "";
    public static final String ORDER_BY_JPQL = "";
    public static final String ORDER_BY_SQL = "";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.it.sincon.sanita.services.model.RispostaPaginata"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.it.sincon.sanita.services.model.RispostaPaginata"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.it.sincon.sanita.services.model.RispostaPaginata"));
    private static ClassLoader _classLoader = StrutturaSanitaria.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
    	RispostaPaginata.class
        };
    private long _primaryKey;
    private int _numFound;
    private int _start;
    private List<T> _data;
    private RispostaPaginata<T> _escapedModel;

    public RispostaPaginataModelImpl() {
    }

//    /**
//     * Converts the soap model instance into a normal model instance.
//     *
//     * @param soapModel the soap model instance to convert
//     * @return the normal model instance
//     */
//    public static StrutturaSanitaria toModel(StrutturaSanitariaSoap soapModel) {
//        if (soapModel == null) {
//            return null;
//        }
//
//        StrutturaSanitaria model = new StrutturaSanitariaImpl();
//
//        model.setIdStruttura(soapModel.getIdStruttura());
//        model.setTipoStruttura(soapModel.getTipoStruttura());
//        model.setTipologia(soapModel.getTipologia());
//        model.setDenominazione(soapModel.getDenominazione());
//        model.setImmagine(soapModel.getImmagine());
//        model.setDescrizione(soapModel.getDescrizione());
//        model.setIndirizzo(soapModel.getIndirizzo());
//        model.setLatitudine(soapModel.getLatitudine());
//        model.setLongitudine(soapModel.getLongitudine());
//        model.setDistanza(soapModel.getDistanza());
//        model.setTelefono(soapModel.getTelefono());
//        model.setEmail(soapModel.getEmail());
//        model.setFax(soapModel.getFax());
//        model.setOrari(soapModel.getOrari());
//
//        return model;
//    }

//    /**
//     * Converts the soap model instances into normal model instances.
//     *
//     * @param soapModels the soap model instances to convert
//     * @return the normal model instances
//     */
//    public static List<StrutturaSanitaria> toModels(
//        StrutturaSanitariaSoap[] soapModels) {
//        if (soapModels == null) {
//            return null;
//        }
//
//        List<StrutturaSanitaria> models = new ArrayList<StrutturaSanitaria>(soapModels.length);
//
//        for (StrutturaSanitariaSoap soapModel : soapModels) {
//            models.add(toModel(soapModel));
//        }
//
//        return models;
//    }

//    @Override
//    public long getPrimaryKey() {
//        return _idRisposta;
//    }
//
//    @Override
//    public void setPrimaryKey(long primaryKey) {
//        setIdStruttura(primaryKey);
//    }
//
//    @Override
//    public Serializable getPrimaryKeyObj() {
//        return _idStruttura;
//    }
//
//    @Override
//    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
//        setPrimaryKey(((Long) primaryKeyObj).longValue());
//    }

    @Override
    public Class<?> getModelClass() {
        return RispostaPaginata.class;
    }

    @Override
    public String getModelClassName() {
        return RispostaPaginata.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("primaryKey", getPrimaryKey());
        attributes.put("numFound", getNumFound());
        attributes.put("start", getStart());
        attributes.put("data", getData());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        int numFound = (Integer) attributes.get("numFound");
        setNumFound(numFound);

        int start = (Integer) attributes.get("start");
        setStart(start);

        List<T> data = (List<T>) attributes.get("data");
        if (data != null) {
            setData(data);
        }
    }
    
    @Override
    public long getPrimaryKey() {
        return _primaryKey;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        _primaryKey = primaryKey;
    }

    @JSON
    @Override
    public int getNumFound() {
        return _numFound;
    }

    @Override
    public void setNumFound(int numFound) {
    	_numFound = numFound;
    }

    @JSON
    @Override
    public int getStart() {
    	return _start;
    }

    @Override
    public void setStart(int start) {
    	_start = start;
    }

    @JSON
    @Override
    public List<T> getData() {
        return _data;
    }

    @Override
    public void setData(List<T> items) {
    	_data = items;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
        		RispostaPaginata.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public RispostaPaginata<T> toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (RispostaPaginata<T>) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
    	RispostaPaginataImpl<T> rispostaPaginataImpl = new RispostaPaginataImpl();

    	rispostaPaginataImpl.setPrimaryKey(getPrimaryKey());
    	rispostaPaginataImpl.setNumFound(getNumFound());
        rispostaPaginataImpl.setStart(getStart());
        rispostaPaginataImpl.setData(getData());

        rispostaPaginataImpl.resetOriginalValues();

        return rispostaPaginataImpl;
    }
    
    @Override
    public Serializable getPrimaryKeyObj() {
        return _primaryKey;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public int compareTo(RispostaPaginata<T> rispostaPaginata) {
        long primaryKey = rispostaPaginata.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof RispostaPaginata)) {
            return false;
        }

        RispostaPaginata<T> strutturaSanitaria = (RispostaPaginata<T>) obj;

        long primaryKey = strutturaSanitaria.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(29);

        sb.append("{numFound=");
        sb.append(getNumFound());
        sb.append(", start=");
        sb.append(getStart());
        sb.append(", data.size()=");
        sb.append(getData().size());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(46);

        sb.append("<model><model-name>");
        sb.append("it.sincon.sanita.services.model.RispostaPaginata");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>numFound</column-name><column-value><![CDATA[");
        sb.append(getNumFound());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>start</column-name><column-value><![CDATA[");
        sb.append(getStart());
        sb.append("]]></column-value></column>");
       sb.append("</model>");

        return sb.toString();
    }
}
