package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.sincon.sanita.services.model.StrutturaSanitariaFiglia;
import it.sincon.sanita.services.service.StrutturaSanitariaFigliaLocalServiceUtil;

/**
 * The extended model base implementation for the StrutturaSanitariaFiglia service. Represents a row in the &quot;SANITAREST_StrutturaSanitariaFiglia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StrutturaSanitariaFigliaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitariaFigliaImpl
 * @see it.sincon.sanita.services.model.StrutturaSanitariaFiglia
 * @generated
 */
public abstract class StrutturaSanitariaFigliaBaseImpl
    extends StrutturaSanitariaFigliaModelImpl
    implements StrutturaSanitariaFiglia {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a struttura sanitaria figlia model instance should use the {@link StrutturaSanitariaFiglia} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StrutturaSanitariaFigliaLocalServiceUtil.addStrutturaSanitariaFiglia(this);
        } else {
            StrutturaSanitariaFigliaLocalServiceUtil.updateStrutturaSanitariaFiglia(this);
        }
    }
}
