package it.sincon.sanita.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.sincon.sanita.services.model.StrutturaSanitaria;
import it.sincon.sanita.services.service.StrutturaSanitariaLocalServiceUtil;

/**
 * The extended model base implementation for the StrutturaSanitaria service. Represents a row in the &quot;SANITAREST_StrutturaSanitaria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StrutturaSanitariaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitariaImpl
 * @see it.sincon.sanita.services.model.StrutturaSanitaria
 * @generated
 */
public abstract class StrutturaSanitariaBaseImpl
    extends StrutturaSanitariaModelImpl implements StrutturaSanitaria {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a struttura sanitaria model instance should use the {@link StrutturaSanitaria} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StrutturaSanitariaLocalServiceUtil.addStrutturaSanitaria(this);
        } else {
            StrutturaSanitariaLocalServiceUtil.updateStrutturaSanitaria(this);
        }
    }
}
