package it.sincon.gepred.protocollo.adoc.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-09-20T17:21:40.163+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ProtocolloServerImplService", 
                  wsdlLocation = "file:/E:/SA_WORKS/WorkSpaces/ARTI/P1-Build/services/protocollo-service/src/main/resources/wsdl/adoc/ProtocolloWebServiceAdoc.wsdl",
                  targetNamespace = "http://impl.server.ws.protocollo.linksmt.it/") 
public class ProtocolloServerImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.ws.protocollo.linksmt.it/", "ProtocolloServerImplService");
    public final static QName ProtocolloServerImplPort = new QName("http://impl.server.ws.protocollo.linksmt.it/", "ProtocolloServerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/SA_WORKS/WorkSpaces/ARTI/P1-Build/services/protocollo-service/src/main/resources/wsdl/adoc/ProtocolloWebServiceAdoc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProtocolloServerImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/SA_WORKS/WorkSpaces/ARTI/P1-Build/services/protocollo-service/src/main/resources/wsdl/adoc/ProtocolloWebServiceAdoc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProtocolloServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProtocolloServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProtocolloServerImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ProtocolloServer
     */
    @WebEndpoint(name = "ProtocolloServerImplPort")
    public ProtocolloServer getProtocolloServerImplPort() {
        return super.getPort(ProtocolloServerImplPort, ProtocolloServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProtocolloServer
     */
    @WebEndpoint(name = "ProtocolloServerImplPort")
    public ProtocolloServer getProtocolloServerImplPort(WebServiceFeature... features) {
        return super.getPort(ProtocolloServerImplPort, ProtocolloServer.class, features);
    }

}
