package it.sincon.gepred.protocollo.adoc.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-09-20T17:21:40.136+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://server.ws.protocollo.linksmt.it/", name = "ProtocolloServer")
@XmlSeeAlso({it.sincon.gepred.protocollo.adoc.bean.ObjectFactory.class, ObjectFactory.class})
public interface ProtocolloServer {

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocollo")
    @ResponseWrapper(localName = "richiestaProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloResponse.Return richiestaProtocollo(
        @WebParam(name = "protocolloRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocollo.ProtocolloRequest protocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "addAllegatura", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.AddAllegatura")
    @ResponseWrapper(localName = "addAllegaturaResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.AddAllegaturaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.AddAllegaturaResponse.Return addAllegatura(
        @WebParam(name = "allegaturaRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.AddAllegatura.AllegaturaRequest allegaturaRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloProvvisorio")
    @ResponseWrapper(localName = "richiestaProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloProvvisorioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloProvvisorioResponse.Return richiestaProtocolloProvvisorio(
        @WebParam(name = "protocolloProvvisorioRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.RichiestaProtocolloProvvisorio.ProtocolloProvvisorioRequest protocolloProvvisorioRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getDestinatariProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetDestinatariProtocollo")
    @ResponseWrapper(localName = "getDestinatariProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetDestinatariProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.GetDestinatariProtocolloResponse.Return getDestinatariProtocollo(
        @WebParam(name = "destinatarioProtocolloRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.GetDestinatariProtocollo.DestinatarioProtocolloRequest destinatarioProtocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "completamentoProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.CompletamentoProtocolloProvvisorio")
    @ResponseWrapper(localName = "completamentoProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.CompletamentoProtocolloProvvisorioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.CompletamentoProtocolloProvvisorioResponse.Return completamentoProtocolloProvvisorio(
        @WebParam(name = "protocolloDaCompletareRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.CompletamentoProtocolloProvvisorio.ProtocolloDaCompletareRequest protocolloDaCompletareRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetProtocollo")
    @ResponseWrapper(localName = "getProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.GetProtocolloResponse.Return getProtocollo(
        @WebParam(name = "protocolloInformazioniRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.GetProtocollo.ProtocolloInformazioniRequest protocolloInformazioniRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getMittenteProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetMittenteProtocollo")
    @ResponseWrapper(localName = "getMittenteProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.sincon.gepred.protocollo.adoc.impl.GetMittenteProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.sincon.gepred.protocollo.adoc.impl.GetMittenteProtocolloResponse.Return getMittenteProtocollo(
        @WebParam(name = "mittenteProtocolloRequest", targetNamespace = "")
        it.sincon.gepred.protocollo.adoc.impl.GetMittenteProtocollo.MittenteProtocolloRequest mittenteProtocolloRequest
    );
}
