package it.sincon.sanita.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CFG_CategorieAbilitate service. Represents a row in the &quot;SANITAREST_CFG_CategorieAbilitate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.sincon.sanita.services.model.impl.CFG_CategorieAbilitateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.sincon.sanita.services.model.impl.CFG_CategorieAbilitateImpl}.
 * </p>
 *
 * @author Sincon
 * @see CFG_CategorieAbilitate
 * @see it.sincon.sanita.services.model.impl.CFG_CategorieAbilitateImpl
 * @see it.sincon.sanita.services.model.impl.CFG_CategorieAbilitateModelImpl
 * @generated
 */
public interface CFG_CategorieAbilitateModel extends BaseModel<CFG_CategorieAbilitate> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a c f g_ categorie abilitate model instance should use the {@link CFG_CategorieAbilitate} interface instead.
     */

    /**
     * Returns the primary key of this c f g_ categorie abilitate.
     *
     * @return the primary key of this c f g_ categorie abilitate
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this c f g_ categorie abilitate.
     *
     * @param primaryKey the primary key of this c f g_ categorie abilitate
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the titolo struttura of this c f g_ categorie abilitate.
     *
     * @return the titolo struttura of this c f g_ categorie abilitate
     */
    @AutoEscape
    public String getTitoloStruttura();

    /**
     * Sets the titolo struttura of this c f g_ categorie abilitate.
     *
     * @param titoloStruttura the titolo struttura of this c f g_ categorie abilitate
     */
    public void setTitoloStruttura(String titoloStruttura);

    /**
     * Returns the denominazione of this c f g_ categorie abilitate.
     *
     * @return the denominazione of this c f g_ categorie abilitate
     */
    @AutoEscape
    public String getDenominazione();

    /**
     * Sets the denominazione of this c f g_ categorie abilitate.
     *
     * @param denominazione the denominazione of this c f g_ categorie abilitate
     */
    public void setDenominazione(String denominazione);

    /**
     * Returns the ordine of this c f g_ categorie abilitate.
     *
     * @return the ordine of this c f g_ categorie abilitate
     */
    public int getOrdine();

    /**
     * Sets the ordine of this c f g_ categorie abilitate.
     *
     * @param ordine the ordine of this c f g_ categorie abilitate
     */
    public void setOrdine(int ordine);

    /**
     * Returns the class name of this c f g_ categorie abilitate.
     *
     * @return the class name of this c f g_ categorie abilitate
     */
    @AutoEscape
    public String getClassName();

    /**
     * Sets the class name of this c f g_ categorie abilitate.
     *
     * @param className the class name of this c f g_ categorie abilitate
     */
    public void setClassName(String className);

    /**
     * Returns the default ricerca of this c f g_ categorie abilitate.
     *
     * @return the default ricerca of this c f g_ categorie abilitate
     */
    public boolean getDefaultRicerca();

    /**
     * Returns <code>true</code> if this c f g_ categorie abilitate is default ricerca.
     *
     * @return <code>true</code> if this c f g_ categorie abilitate is default ricerca; <code>false</code> otherwise
     */
    public boolean isDefaultRicerca();

    /**
     * Sets whether this c f g_ categorie abilitate is default ricerca.
     *
     * @param defaultRicerca the default ricerca of this c f g_ categorie abilitate
     */
    public void setDefaultRicerca(boolean defaultRicerca);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(CFG_CategorieAbilitate cfg_CategorieAbilitate);

    @Override
    public int hashCode();

    @Override
    public CacheModel<CFG_CategorieAbilitate> toCacheModel();

    @Override
    public CFG_CategorieAbilitate toEscapedModel();

    @Override
    public CFG_CategorieAbilitate toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
