package it.sincon.sanita.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the News service. Represents a row in the &quot;SANITAREST_News&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.sincon.sanita.services.model.impl.NewsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.sincon.sanita.services.model.impl.NewsImpl}.
 * </p>
 *
 * @author Sincon
 * @see News
 * @see it.sincon.sanita.services.model.impl.NewsImpl
 * @see it.sincon.sanita.services.model.impl.NewsModelImpl
 * @generated
 */
public interface NewsModel extends BaseModel<News> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a news model instance should use the {@link News} interface instead.
     */

    /**
     * Returns the primary key of this news.
     *
     * @return the primary key of this news
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this news.
     *
     * @param primaryKey the primary key of this news
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the pk of this news.
     *
     * @return the pk of this news
     */
    public long getPk();

    /**
     * Sets the pk of this news.
     *
     * @param pk the pk of this news
     */
    public void setPk(long pk);

    /**
     * Returns the id news of this news.
     *
     * @return the id news of this news
     */
    public long getIdNews();

    /**
     * Sets the id news of this news.
     *
     * @param idNews the id news of this news
     */
    public void setIdNews(long idNews);

    /**
     * Returns the id azienda of this news.
     *
     * @return the id azienda of this news
     */
    @AutoEscape
    public String getIdAzienda();

    /**
     * Sets the id azienda of this news.
     *
     * @param idAzienda the id azienda of this news
     */
    public void setIdAzienda(String idAzienda);

    /**
     * Returns the titolo of this news.
     *
     * @return the titolo of this news
     */
    @AutoEscape
    public String getTitolo();

    /**
     * Sets the titolo of this news.
     *
     * @param titolo the titolo of this news
     */
    public void setTitolo(String titolo);

    /**
     * Returns the immagine of this news.
     *
     * @return the immagine of this news
     */
    @AutoEscape
    public String getImmagine();

    /**
     * Sets the immagine of this news.
     *
     * @param immagine the immagine of this news
     */
    public void setImmagine(String immagine);

    /**
     * Returns the descrizione of this news.
     *
     * @return the descrizione of this news
     */
    @AutoEscape
    public String getDescrizione();

    /**
     * Sets the descrizione of this news.
     *
     * @param descrizione the descrizione of this news
     */
    public void setDescrizione(String descrizione);

    /**
     * Returns the data pubblicazione of this news.
     *
     * @return the data pubblicazione of this news
     */
    public long getDataPubblicazione();

    /**
     * Sets the data pubblicazione of this news.
     *
     * @param dataPubblicazione the data pubblicazione of this news
     */
    public void setDataPubblicazione(long dataPubblicazione);

    /**
     * Returns the autore of this news.
     *
     * @return the autore of this news
     */
    @AutoEscape
    public String getAutore();

    /**
     * Sets the autore of this news.
     *
     * @param autore the autore of this news
     */
    public void setAutore(String autore);

    /**
     * Returns the locale of this news.
     *
     * @return the locale of this news
     */
    @AutoEscape
    public String getLocale();

    /**
     * Sets the locale of this news.
     *
     * @param locale the locale of this news
     */
    public void setLocale(String locale);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(News news);

    @Override
    public int hashCode();

    @Override
    public CacheModel<News> toCacheModel();

    @Override
    public News toEscapedModel();

    @Override
    public News toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
