package it.sincon.sanita.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;
import java.util.List;

/**
 * The base model interface for the RispostaPaginata service. 
 *
 * <p>
 * This interface and its corresponding implementation {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitaria
 * @see it.sincon.sanita.services.model.impl.RispostaPaginataImpl
 * @see it.sincon.sanita.services.model.impl.RispostaPaginataModelImpl
 * @generated
 */
public interface RispostaPaginataModel<T> extends BaseModel<RispostaPaginata<T>> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a struttura sanitaria model instance should use the {@link StrutturaSanitaria} interface instead.
     */

    /**
     * Returns the primary key of this risposta paginata.
     *
     * @return the primary key of this srisposta paginata
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this risposta paginata.
     *
     * @param primaryKey the primary key of this risposta paginata
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the num risultati of this risposta paginata.
     *
     * @return the num risultati of this risposta paginata.
     */
    public int getNumFound();

    /**
     * Sets the num risultati of this risposta paginata.
     *
     * @param numRisultati the num risultati of this risposta paginata
     */
    public void setNumFound(int _numRisultati);
    
    /**
     * Returns the start of this risposta paginata.
     *
     * @return the start of this risposta paginata.
     */
    public int getStart();

    /**
     * Sets the start of this risposta paginata.
     *
     * @param numRisultati the start of this risposta paginata
     */
    public void setStart(int _start);
    
    /**
     * Returns the start of this risposta paginata.
     *
     * @return the start of this risposta paginata.
     */
    public List<T> getData();

    /**
     * Sets the start of this risposta paginata.
     *
     * @param numRisultati the start of this risposta paginata
     */
    public void setData(List<T> _items);
    
    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(RispostaPaginata<T> rispostaPaginata);

    @Override
    public int hashCode();

    @Override
    public CacheModel<RispostaPaginata<T>> toCacheModel();

    @Override
    public RispostaPaginata<T> toEscapedModel();

    @Override
    public RispostaPaginata<T> toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
