package it.sincon.sanita.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StrutturaSanitariaFiglia service. Represents a row in the &quot;SANITAREST_StrutturaSanitariaFiglia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaFigliaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaFigliaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitariaFiglia
 * @see it.sincon.sanita.services.model.impl.StrutturaSanitariaFigliaImpl
 * @see it.sincon.sanita.services.model.impl.StrutturaSanitariaFigliaModelImpl
 * @generated
 */
public interface StrutturaSanitariaFigliaModel extends BaseModel<StrutturaSanitariaFiglia> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a struttura sanitaria figlia model instance should use the {@link StrutturaSanitariaFiglia} interface instead.
     */

    /**
     * Returns the primary key of this struttura sanitaria figlia.
     *
     * @return the primary key of this struttura sanitaria figlia
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this struttura sanitaria figlia.
     *
     * @param primaryKey the primary key of this struttura sanitaria figlia
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the id struttura figlia of this struttura sanitaria figlia.
     *
     * @return the id struttura figlia of this struttura sanitaria figlia
     */
    public long getIdStrutturaFiglia();

    /**
     * Sets the id struttura figlia of this struttura sanitaria figlia.
     *
     * @param idStrutturaFiglia the id struttura figlia of this struttura sanitaria figlia
     */
    public void setIdStrutturaFiglia(long idStrutturaFiglia);

    /**
     * Returns the tipo struttura of this struttura sanitaria figlia.
     *
     * @return the tipo struttura of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getTipoStruttura();

    /**
     * Sets the tipo struttura of this struttura sanitaria figlia.
     *
     * @param tipoStruttura the tipo struttura of this struttura sanitaria figlia
     */
    public void setTipoStruttura(String tipoStruttura);

    /**
     * Returns the denominazione of this struttura sanitaria figlia.
     *
     * @return the denominazione of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getDenominazione();

    /**
     * Sets the denominazione of this struttura sanitaria figlia.
     *
     * @param denominazione the denominazione of this struttura sanitaria figlia
     */
    public void setDenominazione(String denominazione);

    /**
     * Returns the indirizzo of this struttura sanitaria figlia.
     *
     * @return the indirizzo of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getIndirizzo();

    /**
     * Sets the indirizzo of this struttura sanitaria figlia.
     *
     * @param indirizzo the indirizzo of this struttura sanitaria figlia
     */
    public void setIndirizzo(String indirizzo);

    /**
     * Returns the direttore of this struttura sanitaria figlia.
     *
     * @return the direttore of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getDirettore();

    /**
     * Sets the direttore of this struttura sanitaria figlia.
     *
     * @param direttore the direttore of this struttura sanitaria figlia
     */
    public void setDirettore(String direttore);

    /**
     * Returns the responsabile sanitario of this struttura sanitaria figlia.
     *
     * @return the responsabile sanitario of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getResponsabileSanitario();

    /**
     * Sets the responsabile sanitario of this struttura sanitaria figlia.
     *
     * @param responsabileSanitario the responsabile sanitario of this struttura sanitaria figlia
     */
    public void setResponsabileSanitario(String responsabileSanitario);

    /**
     * Returns the telefono of this struttura sanitaria figlia.
     *
     * @return the telefono of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getTelefono();

    /**
     * Sets the telefono of this struttura sanitaria figlia.
     *
     * @param telefono the telefono of this struttura sanitaria figlia
     */
    public void setTelefono(String telefono);

    /**
     * Returns the email of this struttura sanitaria figlia.
     *
     * @return the email of this struttura sanitaria figlia
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this struttura sanitaria figlia.
     *
     * @param email the email of this struttura sanitaria figlia
     */
    public void setEmail(String email);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(StrutturaSanitariaFiglia strutturaSanitariaFiglia);

    @Override
    public int hashCode();

    @Override
    public CacheModel<StrutturaSanitariaFiglia> toCacheModel();

    @Override
    public StrutturaSanitariaFiglia toEscapedModel();

    @Override
    public StrutturaSanitariaFiglia toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
