package it.sincon.sanita.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StrutturaSanitaria service. Represents a row in the &quot;SANITAREST_StrutturaSanitaria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.sincon.sanita.services.model.impl.StrutturaSanitariaImpl}.
 * </p>
 *
 * @author Sincon
 * @see StrutturaSanitaria
 * @see it.sincon.sanita.services.model.impl.StrutturaSanitariaImpl
 * @see it.sincon.sanita.services.model.impl.StrutturaSanitariaModelImpl
 * @generated
 */
public interface StrutturaSanitariaModel extends BaseModel<StrutturaSanitaria> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a struttura sanitaria model instance should use the {@link StrutturaSanitaria} interface instead.
     */

    /**
     * Returns the primary key of this struttura sanitaria.
     *
     * @return the primary key of this struttura sanitaria
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this struttura sanitaria.
     *
     * @param primaryKey the primary key of this struttura sanitaria
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the pk of this struttura sanitaria.
     *
     * @return the pk of this struttura sanitaria
     */
    public long getPk();

    /**
     * Sets the pk of this struttura sanitaria.
     *
     * @param pk the pk of this struttura sanitaria
     */
    public void setPk(long pk);

    /**
     * Returns the id struttura of this struttura sanitaria.
     *
     * @return the id struttura of this struttura sanitaria
     */
    public long getIdStruttura();

    /**
     * Sets the id struttura of this struttura sanitaria.
     *
     * @param idStruttura the id struttura of this struttura sanitaria
     */
    public void setIdStruttura(long idStruttura);

    /**
     * Returns the group ID of this struttura sanitaria.
     *
     * @return the group ID of this struttura sanitaria
     */
    public long getGroupId();

    /**
     * Sets the group ID of this struttura sanitaria.
     *
     * @param groupId the group ID of this struttura sanitaria
     */
    public void setGroupId(long groupId);

    /**
     * Returns the id tipo struttura of this struttura sanitaria.
     *
     * @return the id tipo struttura of this struttura sanitaria
     */
    @AutoEscape
    public String getIdTipoStruttura();

    /**
     * Sets the id tipo struttura of this struttura sanitaria.
     *
     * @param idTipoStruttura the id tipo struttura of this struttura sanitaria
     */
    public void setIdTipoStruttura(String idTipoStruttura);

    /**
     * Returns the tipo struttura of this struttura sanitaria.
     *
     * @return the tipo struttura of this struttura sanitaria
     */
    @AutoEscape
    public String getTipoStruttura();

    /**
     * Sets the tipo struttura of this struttura sanitaria.
     *
     * @param tipoStruttura the tipo struttura of this struttura sanitaria
     */
    public void setTipoStruttura(String tipoStruttura);

    /**
     * Returns the tipologia of this struttura sanitaria.
     *
     * @return the tipologia of this struttura sanitaria
     */
    @AutoEscape
    public String getTipologia();

    /**
     * Sets the tipologia of this struttura sanitaria.
     *
     * @param tipologia the tipologia of this struttura sanitaria
     */
    public void setTipologia(String tipologia);

    /**
     * Returns the denominazione of this struttura sanitaria.
     *
     * @return the denominazione of this struttura sanitaria
     */
    @AutoEscape
    public String getDenominazione();

    /**
     * Sets the denominazione of this struttura sanitaria.
     *
     * @param denominazione the denominazione of this struttura sanitaria
     */
    public void setDenominazione(String denominazione);

    /**
     * Returns the immagine of this struttura sanitaria.
     *
     * @return the immagine of this struttura sanitaria
     */
    @AutoEscape
    public String getImmagine();

    /**
     * Sets the immagine of this struttura sanitaria.
     *
     * @param immagine the immagine of this struttura sanitaria
     */
    public void setImmagine(String immagine);

    /**
     * Returns the descrizione of this struttura sanitaria.
     *
     * @return the descrizione of this struttura sanitaria
     */
    @AutoEscape
    public String getDescrizione();

    /**
     * Sets the descrizione of this struttura sanitaria.
     *
     * @param descrizione the descrizione of this struttura sanitaria
     */
    public void setDescrizione(String descrizione);

    /**
     * Returns the indirizzo of this struttura sanitaria.
     *
     * @return the indirizzo of this struttura sanitaria
     */
    @AutoEscape
    public String getIndirizzo();

    /**
     * Sets the indirizzo of this struttura sanitaria.
     *
     * @param indirizzo the indirizzo of this struttura sanitaria
     */
    public void setIndirizzo(String indirizzo);

    /**
     * Returns the lat of this struttura sanitaria.
     *
     * @return the lat of this struttura sanitaria
     */
    public double getLat();

    /**
     * Sets the lat of this struttura sanitaria.
     *
     * @param lat the lat of this struttura sanitaria
     */
    public void setLat(double lat);

    /**
     * Returns the lng of this struttura sanitaria.
     *
     * @return the lng of this struttura sanitaria
     */
    public double getLng();

    /**
     * Sets the lng of this struttura sanitaria.
     *
     * @param lng the lng of this struttura sanitaria
     */
    public void setLng(double lng);

    /**
     * Returns the distanza of this struttura sanitaria.
     *
     * @return the distanza of this struttura sanitaria
     */
    public double getDistanza();

    /**
     * Sets the distanza of this struttura sanitaria.
     *
     * @param distanza the distanza of this struttura sanitaria
     */
    public void setDistanza(double distanza);

    /**
     * Returns the telefono of this struttura sanitaria.
     *
     * @return the telefono of this struttura sanitaria
     */
    @AutoEscape
    public String getTelefono();

    /**
     * Sets the telefono of this struttura sanitaria.
     *
     * @param telefono the telefono of this struttura sanitaria
     */
    public void setTelefono(String telefono);

    /**
     * Returns the email of this struttura sanitaria.
     *
     * @return the email of this struttura sanitaria
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this struttura sanitaria.
     *
     * @param email the email of this struttura sanitaria
     */
    public void setEmail(String email);

    /**
     * Returns the fax of this struttura sanitaria.
     *
     * @return the fax of this struttura sanitaria
     */
    @AutoEscape
    public String getFax();

    /**
     * Sets the fax of this struttura sanitaria.
     *
     * @param fax the fax of this struttura sanitaria
     */
    public void setFax(String fax);

    /**
     * Returns the orari of this struttura sanitaria.
     *
     * @return the orari of this struttura sanitaria
     */
    @AutoEscape
    public String getOrari();

    /**
     * Sets the orari of this struttura sanitaria.
     *
     * @param orari the orari of this struttura sanitaria
     */
    public void setOrari(String orari);

    /**
     * Returns the locale of this struttura sanitaria.
     *
     * @return the locale of this struttura sanitaria
     */
    @AutoEscape
    public String getLocale();

    /**
     * Sets the locale of this struttura sanitaria.
     *
     * @param locale the locale of this struttura sanitaria
     */
    public void setLocale(String locale);

    /**
     * Returns the stato of this struttura sanitaria.
     *
     * @return the stato of this struttura sanitaria
     */
    public int getStato();

    /**
     * Sets the stato of this struttura sanitaria.
     *
     * @param stato the stato of this struttura sanitaria
     */
    public void setStato(int stato);

    /**
     * Returns the children edotto ospedale collegato of this struttura sanitaria.
     *
     * @return the children edotto ospedale collegato of this struttura sanitaria
     */
    @AutoEscape
    public String getChildrenEdottoOspedaleCollegato();

    /**
     * Sets the children edotto ospedale collegato of this struttura sanitaria.
     *
     * @param childrenEdottoOspedaleCollegato the children edotto ospedale collegato of this struttura sanitaria
     */
    public void setChildrenEdottoOspedaleCollegato(
        String childrenEdottoOspedaleCollegato);

    /**
     * Returns the children edotto ambulatorio of this struttura sanitaria.
     *
     * @return the children edotto ambulatorio of this struttura sanitaria
     */
    @AutoEscape
    public String getChildrenEdottoAmbulatorio();

    /**
     * Sets the children edotto ambulatorio of this struttura sanitaria.
     *
     * @param childrenEdottoAmbulatorio the children edotto ambulatorio of this struttura sanitaria
     */
    public void setChildrenEdottoAmbulatorio(String childrenEdottoAmbulatorio);

    /**
     * Returns the children edotto unita operativa of this struttura sanitaria.
     *
     * @return the children edotto unita operativa of this struttura sanitaria
     */
    @AutoEscape
    public String getChildrenEdottoUnitaOperativa();

    /**
     * Sets the children edotto unita operativa of this struttura sanitaria.
     *
     * @param childrenEdottoUnitaOperativa the children edotto unita operativa of this struttura sanitaria
     */
    public void setChildrenEdottoUnitaOperativa(
        String childrenEdottoUnitaOperativa);

    /**
     * Returns the children edotto unitaps of this struttura sanitaria.
     *
     * @return the children edotto unitaps of this struttura sanitaria
     */
    @AutoEscape
    public String getChildrenEdottoUnitaps();

    /**
     * Sets the children edotto unitaps of this struttura sanitaria.
     *
     * @param childrenEdottoUnitaps the children edotto unitaps of this struttura sanitaria
     */
    public void setChildrenEdottoUnitaps(String childrenEdottoUnitaps);

    /**
     * Returns the relazione ambulatorio of this struttura sanitaria.
     *
     * @return the relazione ambulatorio of this struttura sanitaria
     */
    @AutoEscape
    public String getRelazioneAmbulatorio();

    /**
     * Sets the relazione ambulatorio of this struttura sanitaria.
     *
     * @param relazioneAmbulatorio the relazione ambulatorio of this struttura sanitaria
     */
    public void setRelazioneAmbulatorio(String relazioneAmbulatorio);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(StrutturaSanitaria strutturaSanitaria);

    @Override
    public int hashCode();

    @Override
    public CacheModel<StrutturaSanitaria> toCacheModel();

    @Override
    public StrutturaSanitaria toEscapedModel();

    @Override
    public StrutturaSanitaria toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
